
\c imsDb;
CREATE TABLE IF NOT EXISTS public.users(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    created_by_user_id bigint,
    is_deleted boolean DEFAULT false,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(200) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['USER'::character varying, 'ADMIN'::character varying]::text[]))
);
INSERT INTO public.users(
	created_at, created_by_user_id, is_deleted, updated_at, email, name, password, role)
	VALUES ( NOW(), NULL, false, NOW(), 'admin@gmail.com', 'admin', '$2a$10$9K3ntleoByQIaVclh6qfAuNy/4OEEupz9sAZL0PTkZAeqAuUmhIme','ADMIN')
